name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup toolchains
        run: |
            rustup toolchain install nightly
            rustup component add rust-src
            cargo install cargo-xbuild
            rustup component add llvm-tools-preview
            cargo install bootimage
      - name: Setup test environment
        run: |
            sudo apt install -y qemu-system

      - name: Build with cargo-xbuild
        run: |
            cargo xbuild
            cargo bootimage
      - name: Run unit tests and integration test
        run: |
            cargo xtest
