name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup toolchains
        run: |
            rustup toolchain install nightly
            cargo install cargo-xbuild
            rustup component add llvm-tools-preview
            cargo install bootimage

      - name: Build with cargo-xbuild
        run: |
            cargo xbuild
            cargo bootimage
